### ISSUE TITLE
Musterklausur VSS

### ISSUE THREAD

**Issue by jo-code** [obcode/ob.cs.hm.edu#8]
Hallo Herr Braun @obcode ,
könnten Sie bitte den Link zur Musterklausur VSS fixen? (https://ob.cs.hm.edu/public/vss/exams/KlausurSS18.pdf) Aktuell liefert der Link einen 404.
Das wäre super, vielen Dank!

**Comment by obcode** [comment]
Danke für den Bug-Report.

Ich habe die WS18-Klausur jetzt hochgeladen: https://ob.cs.hm.edu/public/vss/exams/KlausurWS18.pdf
